### ISSUE TITLE
フォーラムを使う？

### ISSUE THREAD

**Issue by kotohodler** [koto-moderator-test/moderator-test#1]
フォーラムを使うべきか？議論。これはテストです
現時点で、
https://github.com/koto-moderator-test/moderator-test/issues/1#issuecomment-389793736
のコメントまで反映しています
=============
・ごにょごにょごにょごにょごにょである
・ごにょごにょごにょごにょごにょである
・ごにょごにょごにょごにょごにょである
・ごにょごにょごにょごにょごにょである
・ごにょごにょごにょごにょごにょである
・ごにょごにょごにょごにょごにょである

=============

**Comment by kotohodler** [comment]
記入はメンバーの私とさしこさんのみ、他の人は閲覧だけとして稼働具合が閲覧できるかテスト

ごにょごにょごにょごにょごにょごにょごにょ

**Comment by kotohodler** [comment]
ごにょごにょごにょごにょごにょごにょ

**Comment by 345-chan** [comment]
ほうほうほう！

**Comment by kotohodler** [comment]
権限周りが細かすぎて泣けます

**Comment by 345-chan** [comment]
慣れれば、細かいのが助かるってやつ
頑張ろう！

**Comment by 345-chan** [comment]
＠1誰かノンメンバーで、どんな挙動するからテスト

**Comment by kotohodler** [comment]
Duplicate of #
![image](https://user-images.githubusercontent.com/35605300/40166253-11ef418a-59f9-11e8-8ef7-8aa782eb4c8e.png)
さしこさんの書き込みが、何番目か分からないです

**Comment by 345-chan** [comment]
1#issuecomment-389789887
TEST

**Comment by 345-chan** [comment]
https://github.com/koto-moderator-test/moderator-test/issues/1#issuecomment-389790348
D&D

**Comment by kotohodler** [comment]
Duplicate of #2
あああ

**Comment by kotohodler** [comment]
Duplicate of #

**Comment by 345-chan** [comment]
https://github.com/koto-moderator-test/moderator-test/issues/1#issuecomment-389791369
日付んとこD&D

**Comment by kotohodler** [comment]
https://github.com/koto-moderator-test/moderator-test/issues/1#issuecomment-389791487
なるほど

**Comment by fkfk** [comment]
hello, KOTO!

**Comment by kotohodler** [comment]
Hello!

- [ あああああ] 

- [いいいいい ]

**Comment by kotohodler** [comment]
オーナーは制限中でも書き込める

**Comment by 345-chan** [comment]
https://github.com/koto-moderator-test/moderator-test/issues/1#issuecomment-389795580
